//@author @pkmelo7

package com.mycompany.telas;

//Importações necessárias
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;
//Fim das importações necessárias

public class Tela_Perfil extends javax.swing.JFrame {
    
    //Declaração de variáveis
        //Variáveis para o movimento do logo Synapse
        final int originalX = 10;
        final int targetX = 150;
        final int step = 10;
        Timer timer = new Timer(20, null);
    
        //Variável para determinar se o checkbox que torna a senha visivel esta ativo ou nao
        boolean showing = false;
    
        //Variaveis para configurar a fonte como poppins
        Font poppins;
        GraphicsEnvironment GE = GraphicsEnvironment.getLocalGraphicsEnvironment();
        
        //Variavel para trazer o icone do projeto
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/icon.png"));
    //Final da declaração de variáveis
    
    //Declaração de métodos 
        //cria o método abrirTela_Login, onde invoca a tela de login e fecha a tela atual
        private void abrirTela_Login() throws FontFormatException, IOException{
        Tela_Login Tela_Login = new Tela_Login();
        this.dispose();
        Tela_Login.setVisible(true);
    }
        //cria o método abrirTela_Sobre, onde invoca a tela de sobre e fecha a tela atual
        private void abrirTela_Sobre() throws FontFormatException, IOException{
            Tela_Sobre Tela_Sobre = new Tela_Sobre();
            this.dispose();
            Tela_Sobre.setVisible(true);
        }
    //Fim da declaração de métodos
    
    public Tela_Perfil() throws FontFormatException, IOException {
        //cria a fonte poppins no projeto
        this.poppins = Font.createFont(Font.TRUETYPE_FONT, new File("src/main/resources/fonts/Poppins-Bold.ttf"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSynapse = new javax.swing.JButton();
        buttonSynapseLogo = new javax.swing.JButton();
        fieldPesquisa = new javax.swing.JTextField();
        buttonXpesq = new javax.swing.JButton();
        buttonSobre = new javax.swing.JButton();
        buttonCursos = new javax.swing.JButton();
        buttonLogin = new javax.swing.JButton();
        fieldNome = new javax.swing.JTextField();
        fieldNasc = new javax.swing.JTextField();
        fieldUser = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        fieldSenha = new javax.swing.JPasswordField();
        checkboxSenha = new javax.swing.JCheckBox();
        buttonEditSenha = new javax.swing.JButton();
        buttonEditPerfil = new javax.swing.JButton();
        buttonSalvarPerfil = new javax.swing.JButton();
        buttonPR = new javax.swing.JButton();
        buttonXTelas = new javax.swing.JButton();
        labelPerfil = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Synapse Connect");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(icon.getImage());
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 750));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        buttonSynapse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/NomeLogo.png"))); // NOI18N
        buttonSynapse.setBorder(null);
        buttonSynapse.setBorderPainted(false);
        buttonSynapse.setContentAreaFilled(false);
        buttonSynapse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSynapse.setFocusPainted(false);
        buttonSynapse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSynapseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSynapseMouseExited(evt);
            }
        });
        buttonSynapse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSynapseActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSynapse);
        buttonSynapse.setBounds(30, 0, 260, 160);

        buttonSynapseLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Formas/IconSynapse.png"))); // NOI18N
        buttonSynapseLogo.setBorder(null);
        buttonSynapseLogo.setBorderPainted(false);
        buttonSynapseLogo.setContentAreaFilled(false);
        buttonSynapseLogo.setFocusPainted(false);
        jPanel1.add(buttonSynapseLogo);
        buttonSynapseLogo.setBounds(10, 0, 170, 160);

        fieldPesquisa.setBackground(new java.awt.Color(224, 222, 222));
        fieldPesquisa.setFont(poppins.deriveFont(14f));
        fieldPesquisa.setForeground(new java.awt.Color(128, 128, 128));
        fieldPesquisa.setText("Pesquisar:");
        fieldPesquisa.setBorder(null);
        fieldPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldPesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldPesquisaFocusLost(evt);
            }
        });
        fieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(fieldPesquisa);
        fieldPesquisa.setBounds(380, 50, 380, 50);

        buttonXpesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/X.png"))); // NOI18N
        buttonXpesq.setBorder(null);
        buttonXpesq.setBorderPainted(false);
        buttonXpesq.setContentAreaFilled(false);
        buttonXpesq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXpesq.setFocusPainted(false);
        buttonXpesq.setMaximumSize(new java.awt.Dimension(86, 19));
        buttonXpesq.setMinimumSize(new java.awt.Dimension(86, 19));
        buttonXpesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonXpesqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonXpesqMouseExited(evt);
            }
        });
        buttonXpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXpesqActionPerformed(evt);
            }
        });
        jPanel1.add(buttonXpesq);
        buttonXpesq.setBounds(780, 60, 40, 30);

        buttonSobre.setFont(poppins.deriveFont(24f));
        buttonSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/Sobre.png"))); // NOI18N
        buttonSobre.setBorder(null);
        buttonSobre.setBorderPainted(false);
        buttonSobre.setContentAreaFilled(false);
        buttonSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSobre.setFocusPainted(false);
        buttonSobre.setMaximumSize(new java.awt.Dimension(86, 19));
        buttonSobre.setMinimumSize(new java.awt.Dimension(86, 19));
        buttonSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSobreMouseExited(evt);
            }
        });
        buttonSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSobreActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSobre);
        buttonSobre.setBounds(930, 60, 80, 30);

        buttonCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/Cursos.png"))); // NOI18N
        buttonCursos.setBorder(null);
        buttonCursos.setBorderPainted(false);
        buttonCursos.setContentAreaFilled(false);
        buttonCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCursos.setFocusPainted(false);
        buttonCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCursosMouseExited(evt);
            }
        });
        buttonCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCursosActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCursos);
        buttonCursos.setBounds(1030, 60, 100, 30);

        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/Login.png"))); // NOI18N
        buttonLogin.setBorder(null);
        buttonLogin.setBorderPainted(false);
        buttonLogin.setContentAreaFilled(false);
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.setFocusPainted(false);
        buttonLogin.setMaximumSize(new java.awt.Dimension(86, 19));
        buttonLogin.setMinimumSize(new java.awt.Dimension(86, 19));
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonLoginMouseExited(evt);
            }
        });
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLogin);
        buttonLogin.setBounds(1150, 50, 170, 55);

        fieldNome.setBackground(new java.awt.Color(224, 222, 222));
        fieldNome.setFont(poppins.deriveFont(14f)
        );
        fieldNome.setForeground(new java.awt.Color(128, 128, 128));
        fieldNome.setText("Nome");
        fieldNome.setBorder(null);
        fieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNomeFocusLost(evt);
            }
        });
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });
        jPanel1.add(fieldNome);
        fieldNome.setBounds(760, 303, 380, 45);

        fieldNasc.setBackground(new java.awt.Color(224, 222, 222));
        fieldNasc.setFont(poppins.deriveFont(14f));
        fieldNasc.setForeground(new java.awt.Color(128, 128, 128));
        fieldNasc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldNasc.setText("Nascimento                                           Formato: 00/00/0000");
        fieldNasc.setToolTipText("");
        fieldNasc.setBorder(null);
        fieldNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNascFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNascFocusLost(evt);
            }
        });
        fieldNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNascActionPerformed(evt);
            }
        });
        jPanel1.add(fieldNasc);
        fieldNasc.setBounds(760, 385, 380, 40);

        fieldUser.setBackground(new java.awt.Color(224, 222, 222));
        fieldUser.setFont(poppins.deriveFont(14f));
        fieldUser.setForeground(new java.awt.Color(128, 128, 128));
        fieldUser.setText("Usuário");
        fieldUser.setBorder(null);
        fieldUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldUserFocusLost(evt);
            }
        });
        fieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserActionPerformed(evt);
            }
        });
        jPanel1.add(fieldUser);
        fieldUser.setBounds(760, 460, 400, 45);

        fieldEmail.setBackground(new java.awt.Color(224, 222, 222));
        fieldEmail.setFont(poppins.deriveFont(14f));
        fieldEmail.setForeground(new java.awt.Color(128, 128, 128));
        fieldEmail.setText("E-mail");
        fieldEmail.setBorder(null);
        fieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldEmailFocusLost(evt);
            }
        });
        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(fieldEmail);
        fieldEmail.setBounds(760, 540, 400, 45);

        labelSenha.setFont(poppins.deriveFont(14f));
        labelSenha.setForeground(new java.awt.Color(128, 128, 128));
        labelSenha.setText("Senha:");
        jPanel1.add(labelSenha);
        labelSenha.setBounds(760, 620, 50, 40);

        fieldSenha.setBackground(new java.awt.Color(224, 222, 222));
        fieldSenha.setFont(poppins.deriveFont(14f));
        fieldSenha.setForeground(new java.awt.Color(128, 128, 128));
        fieldSenha.setBorder(null);
        fieldSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldSenhaFocusLost(evt);
            }
        });
        fieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSenhaActionPerformed(evt);
            }
        });
        fieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSenhaKeyReleased(evt);
            }
        });
        jPanel1.add(fieldSenha);
        fieldSenha.setBounds(760, 620, 390, 40);

        checkboxSenha.setBorder(null);
        checkboxSenha.setContentAreaFilled(false);
        checkboxSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkboxSenha.setFocusPainted(false);
        checkboxSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/SenhaMostrar.png"))); // NOI18N
        checkboxSenha.setVisible(false);
        checkboxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(checkboxSenha);
        checkboxSenha.setBounds(1150, 620, 20, 40);

        buttonEditSenha.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        buttonEditSenha.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/EditSenha.png"))); // NOI18N
        buttonEditSenha.setBorder(null);
        buttonEditSenha.setBorderPainted(false);
        buttonEditSenha.setContentAreaFilled(false);
        buttonEditSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEditSenha.setFocusPainted(false);
        buttonEditSenha.setVisible(false);
        buttonEditSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEditSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEditSenhaMouseExited(evt);
            }
        });
        buttonEditSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEditSenha);
        buttonEditSenha.setBounds(1065, 685, 120, 40);

        buttonEditPerfil.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        buttonEditPerfil.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/Seta.png"))); // NOI18N
        buttonEditPerfil.setBorder(null);
        buttonEditPerfil.setBorderPainted(false);
        buttonEditPerfil.setContentAreaFilled(false);
        buttonEditPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEditPerfil.setFocusPainted(false);
        buttonEditPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonEditPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonEditPerfilMouseExited(evt);
            }
        });
        buttonEditPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEditPerfil);
        buttonEditPerfil.setBounds(60, 664, 180, 50);

        buttonSalvarPerfil.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        buttonSalvarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        buttonSalvarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/EditPerfilSalvar.png"))); // NOI18N
        buttonSalvarPerfil.setBorder(null);
        buttonSalvarPerfil.setBorderPainted(false);
        buttonSalvarPerfil.setContentAreaFilled(false);
        buttonSalvarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSalvarPerfil.setFocusPainted(false);
        buttonSalvarPerfil.setVisible(false);
        buttonSalvarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSalvarPerfil);
        buttonSalvarPerfil.setBounds(60, 664, 180, 50);

        buttonPR.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        buttonPR.setForeground(new java.awt.Color(255, 255, 255));
        buttonPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/IconSynapsePreto.png"))); // NOI18N
        buttonPR.setBorder(null);
        buttonPR.setBorderPainted(false);
        buttonPR.setContentAreaFilled(false);
        buttonPR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPR.setFocusPainted(false);
        buttonPR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonPRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonPRMouseExited(evt);
            }
        });
        buttonPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPRActionPerformed(evt);
            }
        });
        jPanel1.add(buttonPR);
        buttonPR.setBounds(1270, 655, 80, 70);

        buttonXTelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/XFecharTelas.png"))); // NOI18N
        buttonXTelas.setBorder(null);
        buttonXTelas.setBorderPainted(false);
        buttonXTelas.setContentAreaFilled(false);
        buttonXTelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXTelas.setFocusPainted(false);
        buttonXTelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonXTelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonXTelasMouseExited(evt);
            }
        });
        buttonXTelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXTelasActionPerformed(evt);
            }
        });
        jPanel1.add(buttonXTelas);
        buttonXTelas.setBounds(1280, 0, 86, 25);

        labelPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Formas/MeuPerfil.png"))); // NOI18N
        jPanel1.add(labelPerfil);
        labelPerfil.setBounds(50, 205, 200, 70);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FundosTelas/FundoPerfil.png"))); // NOI18N
        jPanel1.add(fundo);
        fundo.setBounds(0, -16, 1370, 800);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 768);

        setBounds(-6, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

//---------------------------------------------------------------------------------------------------------------------------------
    
//Comandos do field "Nome"
    //<null>
    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed
    //Faz com que a palavra "Nome" desapareça de dentro do field quando o foco é retomado
    private void fieldNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNomeFocusGained
        // TODO add your handling code here:
        if (fieldNome.getText().equals("Nome")) {
            fieldNome.setText("");
            fieldNome.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldNomeFocusGained
    //Faz com que a palavra "Nome" apareça dentro do field quando o foco é perdido
    private void fieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNomeFocusLost
        // TODO add your handling code here:
        if (fieldNome.getText().isEmpty()) {
            fieldNome.setForeground(Color.GRAY);
            fieldNome.setText("Nome");
        }
    }//GEN-LAST:event_fieldNomeFocusLost
//Fim dos comandos do field "Nome"
    
//---------------------------------------------------------------------------------------------------------------------------------

//Início dos comandos do field "Nascimento"
    //<null>
    private void fieldNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNascActionPerformed
    //Faz com que a palavra "Nascimento" desapareça de dentro do field quando o foco é retomado
    private void fieldNascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNascFocusGained
        // TODO add your handling code here:
        if (fieldNasc.getText().equals("Nascimento                                           Formato: 00/00/0000")) {
            fieldNasc.setText("");
            fieldNasc.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldNascFocusGained
    //Faz com que a palavra "Nascimento" apareça dentro do field quando o foco é perdido
    private void fieldNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNascFocusLost
        // TODO add your handling code here:
        if (fieldNasc.getText().isEmpty()) {
            fieldNasc.setForeground(Color.GRAY);
            fieldNasc.setText("Nascimento                                           Formato: 00/00/0000");
        }
    }//GEN-LAST:event_fieldNascFocusLost
//Fim dos comandos do field "Nascimento"
    
//---------------------------------------------------------------------------------------------------------------------------------

//Início dos comandos do field "Usuário"
    //<null>
    private void fieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserActionPerformed
    //Faz com que a palavra "Usuário" desapareça de dentro do field quando o foco é retomado
    private void fieldUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUserFocusGained
        // TODO add your handling code here:
        if (fieldUser.getText().equals("Usuário")) {
            fieldUser.setText("");
            fieldUser.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldUserFocusGained
    //Faz com que a palavra "Usuário" apareça dentro do field quando o foco é perdido
    private void fieldUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldUserFocusLost
        // TODO add your handling code here:
        if (fieldUser.getText().isEmpty()) {
            fieldUser.setForeground(Color.GRAY);
            fieldUser.setText("Usuário");
        }
    }//GEN-LAST:event_fieldUserFocusLost
//Fim dos comandos do field "Usuário"

//---------------------------------------------------------------------------------------------------------------------------------

//Início dos comandos do field "E-mail"
   //<null>
    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed
    //Faz com que a palavra "E-mail" desapareça de dentro do field quando o foco é retomado
    private void fieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldEmailFocusGained
        // TODO add your handling code here:
        if (fieldEmail.getText().equals("E-mail")) {
            fieldEmail.setText("");
            fieldEmail.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldEmailFocusGained
    //Faz com que a palavra "E-mail" apareça dentro do field quando o foco é perdido
    private void fieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldEmailFocusLost
        // TODO add your handling code here:
        if (fieldEmail.getText().isEmpty()) {
            fieldEmail.setForeground(Color.GRAY);
            fieldEmail.setText("E-mail");
        }
    }//GEN-LAST:event_fieldEmailFocusLost
//Fim dos comandos do field "E-mail"

//---------------------------------------------------------------------------------------------------------------------------------

//Início dos comandos do field "Senha"
   //<null>
    private void fieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSenhaActionPerformed
    //Faz com que a palavra "Senha" desapareça de dentro do field quando o foco é retomado
    private void fieldSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSenhaFocusGained
        // TODO add your handling code here:
        if (labelSenha.getText().equals("Senha:")) {
            labelSenha.setText("");
            fieldSenha.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldSenhaFocusGained
    //Faz com que a palavra "Senha" apareça dentro do field quando o foco é perdido
    private void fieldSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSenhaFocusLost
        // TODO add your handling code here:
        if (labelSenha.getText().isEmpty() || fieldSenha.getText().isEmpty()) {
            labelSenha.setForeground(Color.GRAY);
            labelSenha.setText("Senha:");
        }
    }//GEN-LAST:event_fieldSenhaFocusLost
    //Caso algo seja digitado no fieldSenha, seta o labelSenha como nulo e o checkbox como Mostrar e visível
    //Caso nada seja digitado no fieldSenha ou o que foi digitado no fieldSenha seja apagado, seta o checkbox como invisível
    private void fieldSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSenhaKeyReleased
        // TODO add your handling code here:
        if (fieldSenha.getPassword().length > 0) 
        {
            labelSenha.setText(" ");
            checkboxSenha.setVisible(true);
            Icon MostrarSenha = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/SenhaMostrar.png"));
            checkboxSenha.setIcon(MostrarSenha);
        }
        else
        {
            checkboxSenha.setVisible(false);
        }   
    }//GEN-LAST:event_fieldSenhaKeyReleased
    //Seta os icons OcultarSenha e MostrarSenha
    //Caso showing = false: seta o field "Senha" como "*" e o checkbox como Ocultar
    //Caso showing = true: seta o field "Senha" como char e o checkbox como Mostrar
    private void checkboxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxSenhaActionPerformed
        // TODO add your handling code here:
        Icon OcultarSenha = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/SenhaOcultar.png"));
        Icon MostrarSenha = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/SenhaMostrar.png"));
                
        if(showing)
        {
            fieldSenha.setEchoChar('*');
            checkboxSenha.setIcon(MostrarSenha);
        }
        else
        {
            fieldSenha.setEchoChar((char) 0);
            checkboxSenha.setIcon(OcultarSenha);
        }
        showing = !showing;
    }//GEN-LAST:event_checkboxSenhaActionPerformed
//Fim dos comandos do field "Senha"

//---------------------------------------------------------------------------------------------------------------------------------

//Início dos comandos do field "Pesquisar"
    //<null>
    private void fieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPesquisaActionPerformed
    //Faz com que a palavra "Pesquisar" desapareça de dentro do field quando o foco é retomado
    private void fieldPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPesquisaFocusGained
        // TODO add your handling code here:
        if (fieldPesquisa.getText().equals("Pesquisar:")) {
            fieldPesquisa.setText("");
            fieldPesquisa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fieldPesquisaFocusGained
    //Faz com que a palavra "Pesquisar" apareça dentro do field quando o foco é perdido
    private void fieldPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldPesquisaFocusLost
        // TODO add your handling code here:
        if (fieldPesquisa.getText().isEmpty()) {
            fieldPesquisa.setForeground(Color.GRAY);
            fieldPesquisa.setText("Pesquisar:");
        }
    }//GEN-LAST:event_fieldPesquisaFocusLost
//Início dos comandos do botão "X" para o field "Pesquisar"
    //Faz com que ao clicar no botão "X", tudo que possa estar escrito dentro do field "Pesquisar" seja apagado e o field seja setado novamente como "Pesquisar" na cor cinza
    private void buttonXpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXpesqActionPerformed
        // TODO add your handling code here:
        fieldPesquisa.setForeground(Color.GRAY);
        fieldPesquisa.setText("Pesquisar:");
    }//GEN-LAST:event_buttonXpesqActionPerformed
    //Faz o botão de X para o field "Pesquisar" ficar Azul ao passar o mouse por cima
    private void buttonXpesqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXpesqMouseEntered
        // TODO add your handling code here:
        ImageIcon XpesqAzul = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/XAzul.png"));
        buttonXpesq.setIcon(XpesqAzul);
    }//GEN-LAST:event_buttonXpesqMouseEntered
    //Faz o botão de X para o field "Pesquisar" voltar à cor padrão ao tirar o mouse de cima
    private void buttonXpesqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXpesqMouseExited
        // TODO add your handling code here:
        ImageIcon Xpesq = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/X.png"));
        buttonXpesq.setIcon(Xpesq);
    }//GEN-LAST:event_buttonXpesqMouseExited
//Fim dos comandos do botão "X" para o field "Pesquisar"
//Fim dos comandos do field "Pesquisar"
    
//---------------------------------------------------------------------------------------------------------------------------------
   
//Início dos comandos do botão do Logo "Synapse Connect"
    //<null>
    private void buttonSynapseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSynapseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSynapseActionPerformed
    //Move o Logo "Synapse Connect" à posição final enquanto o mouse estiver em cima
    private void buttonSynapseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSynapseMouseEntered
        // TODO add your handling code here:
        timer.stop();
        timer = new Timer(20, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                int x = buttonSynapseLogo.getX();
                int y = buttonSynapseLogo.getY();

                if (x < targetX) {
                    buttonSynapseLogo.setLocation(x + step, y);
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_buttonSynapseMouseEntered
    //Move o Logo "Synapse Connect" à posição inicial quando o mouse sair de cima
    private void buttonSynapseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSynapseMouseExited
        // TODO add your handling code here:
        timer.stop();
        timer = new Timer(20, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                int x = buttonSynapseLogo.getX();
                int y = buttonSynapseLogo.getY();

                if (x > originalX) {
                    buttonSynapseLogo.setLocation(x - step, y);
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_buttonSynapseMouseExited
//Fim dos comandos do botão do Logo "Synapse Connect"

//---------------------------------------------------------------------------------------------------------------------------------
    
//Início dos comandos do botão "Sobre"
    //<null>
    private void buttonSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSobreActionPerformed
    //Faz o botão Sobre ficar Azul ao passar o mouse por cima
    private void buttonSobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSobreMouseEntered
        // TODO add your handling code here:
        ImageIcon SobreAzul = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/SobreAzul.png"));
        buttonSobre.setIcon(SobreAzul);
    }//GEN-LAST:event_buttonSobreMouseEntered
    //Faz o botão Sobre voltar à cor padrão ao tirar o mouse de cima
    private void buttonSobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSobreMouseExited
        // TODO add your handling code here:
        ImageIcon Sobre = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/Sobre.png"));
        buttonSobre.setIcon(Sobre);
    }//GEN-LAST:event_buttonSobreMouseExited
//Fim dos comandos do botão "Sobre"

//---------------------------------------------------------------------------------------------------------------------------------
  
//Início dos comandos do botão "Cursos"
    //<null>
    private void buttonCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCursosActionPerformed
    //Faz o botão Cursos ficar Azul ao passar o mouse por cima
    private void buttonCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCursosMouseEntered
        // TODO add your handling code here:
        ImageIcon CursosAzul = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/CursosAzul.png"));
        buttonCursos.setIcon(CursosAzul);
    }//GEN-LAST:event_buttonCursosMouseEntered
    //Faz o botão Sobre voltar à cor padrão ao tirar o mouse de cima
    private void buttonCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCursosMouseExited
        // TODO add your handling code here:
        ImageIcon Cursos = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/Cursos.png"));
        buttonCursos.setIcon(Cursos);
    }//GEN-LAST:event_buttonCursosMouseExited
//Fim dos comandos do botão "Cursos"

//---------------------------------------------------------------------------------------------------------------------------------
 
//Início dos comandos do botão "Entrar"
    //Faz com que ao clicar no botao "Entrar", o método abrirTela_Login seja executado
    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed

        try {
            // TODO add your handling code here:
            abrirTela_Login();
        } catch (FontFormatException ex) {
            Logger.getLogger(Tela_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Tela_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonLoginActionPerformed
    //Faz o botão Entrar ficar Azul ao passar o mouse por cima
    private void buttonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseEntered
        // TODO add your handling code here:
        ImageIcon LoginAzul = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/LoginAzul.png"));
        buttonLogin.setIcon(LoginAzul);
    }//GEN-LAST:event_buttonLoginMouseEntered
    //Faz o botão Entrar voltar à cor padrão ao tirar o mouse de cima
    private void buttonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseExited
        // TODO add your handling code here:
        ImageIcon Login = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/Login.png"));
        buttonLogin.setIcon(Login);
    }//GEN-LAST:event_buttonLoginMouseExited
//Fim dos comandos do botão "Entrar"

//---------------------------------------------------------------------------------------------------------------------------------

//Início dos comandos do botão "Editar Senha"
    //<null>
    private void buttonEditSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditSenhaActionPerformed
    //Faz o botão Cadastrar ficar Azul ao passar o mouse por cima
    private void buttonEditSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditSenhaMouseEntered
        // TODO add your handling code here:
        ImageIcon CadastrarAzul = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/EditSenhaAzul.png"));
        buttonEditSenha.setIcon(CadastrarAzul);
    }//GEN-LAST:event_buttonEditSenhaMouseEntered
    //Faz o botão Cadastrar voltar a cor padrão ao tirar o mouse de cima
    private void buttonEditSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditSenhaMouseExited
        // TODO add your handling code here:
        ImageIcon Cadastrar = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/EditSenha.png"));
        buttonEditSenha.setIcon(Cadastrar);
    }//GEN-LAST:event_buttonEditSenhaMouseExited
//Fim dos comandos do botão "Editar Senha"

//---------------------------------------------------------------------------------------------------------------------------------

//Início dos comandos do botão "P&R"
    //<null>
    private void buttonPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPRActionPerformed
    //Faz o botão P&R ficar Azul ao passar o mouse por cima
    private void buttonPRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPRMouseEntered
        // TODO add your handling code here:
        ImageIcon PRAzul = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/IconSynapseAzul.png"));
        buttonPR.setIcon(PRAzul);
    }//GEN-LAST:event_buttonPRMouseEntered
    //Faz o botão P&R voltar a cor padrão ao tirar o mouse de cima
    private void buttonPRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPRMouseExited
        // TODO add your handling code here:
        ImageIcon PR = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/IconSynapsePreto.png"));
        buttonPR.setIcon(PR);
    }//GEN-LAST:event_buttonPRMouseExited
//Fim dos comandos do botão "P&R"

//---------------------------------------------------------------------------------------------------------------------------------

//Início dos comandos do botão "Seta"/"Editar Perfil"
    //Altera o icone do botao para "Editar Perfil" quando o mouse passa por cima
    private void buttonEditPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditPerfilMouseEntered
        // TODO add your handling code here:
        ImageIcon SetaCadastrar = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/EditPerfil.png"));
        buttonEditPerfil.setIcon(SetaCadastrar);
    }//GEN-LAST:event_buttonEditPerfilMouseEntered
    //Altera o icone do botao de volta para Seta quando o mouse sai do botao
    private void buttonEditPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditPerfilMouseExited
        // TODO add your handling code here:
        ImageIcon Seta = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/Seta.png"));
        buttonEditPerfil.setIcon(Seta);
    }//GEN-LAST:event_buttonEditPerfilMouseExited
    //Ações do botao (declaradas dentro das chaves)
    private void buttonEditPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditPerfilActionPerformed
        // TODO add your handling code here:
        //traz o icone para alterar o texto na barra lateral azul
        ImageIcon EditarPerfil = new ImageIcon(getClass().getClassLoader().getResource("images/Formas/EditarPerfil.png"));
        //altera o texto "Meu Perfil" para "Editar Perfil" ao apertar no botao
        labelPerfil.setIcon(EditarPerfil);
        //esconde o botao editar perfil
        buttonEditPerfil.setVisible(false);
        //torna o botao salvar perfil visivel
        buttonSalvarPerfil.setVisible(true);
        //torna o botao editar senha visivel
        buttonEditSenha.setVisible(true);
    }//GEN-LAST:event_buttonEditPerfilActionPerformed
//Fim dos comandos do botão "Seta"/"Editar Perfil"

//---------------------------------------------------------------------------------------------------------------------------------
    
//Início dos comandos do botão X para fechar a aplicação
    //Faz com que o botao mude de icone e fique vermelho ao passar o mouse por cima
    private void buttonXTelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXTelasMouseEntered
        // TODO add your handling code here:
        ImageIcon XTelasVerm = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/XFecharTelasVerm.png"));
        buttonXTelas.setIcon(XTelasVerm);
    }//GEN-LAST:event_buttonXTelasMouseEntered
    //Faz com que o botao mude de icone e volte a cor padrao ao tirar o mouse de cima
    private void buttonXTelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXTelasMouseExited
        // TODO add your handling code here:
        ImageIcon XTelas = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/XFecharTelas.png"));
        buttonXTelas.setIcon(XTelas);
    }//GEN-LAST:event_buttonXTelasMouseExited
    //Fecha a aplicação ao apertar no botao X
    private void buttonXTelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXTelasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonXTelasActionPerformed
//Fim dos comandos do botão X para fechar a aplicação

//---------------------------------------------------------------------------------------------------------------------------------
    
//Início dos comandos do botão X para fechar a aplicação
    //Ações do botao (declaradas dentro das chaves)
    private void buttonSalvarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarPerfilActionPerformed
        // TODO add your handling code here:
        //traz o icone para alterar o texto na barra lateral
        ImageIcon Perfil = new ImageIcon(getClass().getClassLoader().getResource("images/Formas/MeuPerfil.png"));
        //altera o texto "Editar Perfil" para "Meu Perfil" ao apertar no botao
        labelPerfil.setIcon(Perfil);
        //esconde o botao salvar alteracoes
        buttonSalvarPerfil.setVisible(false);
        //esconde o botao editar senha 
        buttonEditSenha.setVisible(false);
        //torna o botao editar perfil visivel
        buttonEditPerfil.setVisible(true);
    }//GEN-LAST:event_buttonSalvarPerfilActionPerformed
//Fim dos comandos do botão X para fechar a aplicação

//---------------------------------------------------------------------------------------------------------------------------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_Perfil().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(Tela_Perfil.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Tela_Perfil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCursos;
    private javax.swing.JButton buttonEditPerfil;
    private javax.swing.JButton buttonEditSenha;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonPR;
    private javax.swing.JButton buttonSalvarPerfil;
    private javax.swing.JButton buttonSobre;
    private javax.swing.JButton buttonSynapse;
    private javax.swing.JButton buttonSynapseLogo;
    private javax.swing.JButton buttonXTelas;
    private javax.swing.JButton buttonXpesq;
    private javax.swing.JCheckBox checkboxSenha;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNasc;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldPesquisa;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel fundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPerfil;
    private javax.swing.JLabel labelSenha;
    // End of variables declaration//GEN-END:variables
}
