//@author @pkmelo7

package com.mycompany.telas.admin;

//Importações necessárias
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
//Fim das importações necessárias

public class Tela_Admin2 extends javax.swing.JFrame {
    
    //Declaração de variáveis 
        //variavel para uso da fonte digital7
        Font digital7;
        GraphicsEnvironment GE = GraphicsEnvironment.getLocalGraphicsEnvironment();
        
        //Variavel para trazer o icone do projeto
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/icon.png")); 
    //Final da declaração de variáveis
    
    //Declaração de métodos
        public void abrirTelaAdminCadastrar1() throws FontFormatException, IOException
        {
            Tela_AdminCadastrar1 Cadastrar = new Tela_AdminCadastrar1();
            Cadastrar.setVisible(true);
            this.dispose();
        }
        
        public void abrirTelaAdminCrud1() throws FontFormatException, IOException
        {
            Tela_AdminCrud1 Crud = new Tela_AdminCrud1();
            Crud.setVisible(true);
            this.dispose();
        }
        
    //Fim da declaração de métodos
        
    public Tela_Admin2() throws FontFormatException, IOException {
        //cria a fonte digital7 no projeto
        this.digital7 = Font.createFont(Font.TRUETYPE_FONT, new File("src/main/resources/fonts/digital-7.ttf"));
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaAdmin = new javax.swing.JPanel();
        messageLabel1 = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JButton();
        buttonCrud = new javax.swing.JButton();
        buttonXTelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Synapse Connect");
        setBackground(new java.awt.Color(224, 222, 222));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(icon.getImage());
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 750));
        getContentPane().setLayout(null);

        telaAdmin.setBackground(new java.awt.Color(0, 0, 0));
        telaAdmin.setForeground(new java.awt.Color(0, 0, 0));
        telaAdmin.setLayout(null);

        messageLabel1.setBackground(new java.awt.Color(0, 0, 0));
        messageLabel1.setFont(digital7.deriveFont(100f));
        messageLabel1.setForeground(new java.awt.Color(0, 255, 8));
        messageLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        messageLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        String message = "O que gostaria de fazer?";
        typingEffect(messageLabel1, message, buttonCadastrar, buttonCrud);
        telaAdmin.add(messageLabel1);
        messageLabel1.setBounds(0, 0, 1366, 201);

        buttonCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        buttonCadastrar.setFont(digital7.deriveFont(75f));
        buttonCadastrar.setForeground(new java.awt.Color(0, 255, 8));
        buttonCadastrar.setBorder(null);
        buttonCadastrar.setBorderPainted(false);
        buttonCadastrar.setContentAreaFilled(false);
        buttonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCadastrar.setFocusPainted(false);
        buttonCadastrar.setHorizontalAlignment(SwingConstants.LEFT);
        buttonCadastrar.setVisible(false);
        buttonCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCadastrarMouseExited(evt);
            }
        });
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        telaAdmin.add(buttonCadastrar);
        buttonCadastrar.setBounds(50, 325, 1316, 90);

        buttonCrud.setBackground(new java.awt.Color(0, 0, 0));
        buttonCrud.setFont(digital7.deriveFont(75f));
        buttonCrud.setForeground(new java.awt.Color(0, 255, 8));
        buttonCrud.setBorder(null);
        buttonCrud.setBorderPainted(false);
        buttonCrud.setContentAreaFilled(false);
        buttonCrud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCrud.setFocusPainted(false);
        buttonCrud.setHorizontalAlignment(SwingConstants.LEFT);
        buttonCrud.setVisible(false);
        buttonCrud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCrudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCrudMouseExited(evt);
            }
        });
        buttonCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrudActionPerformed(evt);
            }
        });
        telaAdmin.add(buttonCrud);
        buttonCrud.setBounds(50, 475, 1316, 90);

        buttonXTelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/XFecharTelasAdmin.png"))); // NOI18N
        buttonXTelas.setBorder(null);
        buttonXTelas.setBorderPainted(false);
        buttonXTelas.setContentAreaFilled(false);
        buttonXTelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXTelas.setFocusPainted(false);
        buttonXTelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonXTelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonXTelasMouseExited(evt);
            }
        });
        buttonXTelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXTelasActionPerformed(evt);
            }
        });
        telaAdmin.add(buttonXTelas);
        buttonXTelas.setBounds(1280, 0, 86, 25);

        getContentPane().add(telaAdmin);
        telaAdmin.setBounds(0, 0, 1366, 768);

        setBounds(-6, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents
//---------------------------------------------------------------------------------------------------------------------------------

//Inicio dos comandos do botao "> Cadastrar"
    //<null>
    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
            try {
                // TODO add your handling code here:
                abrirTelaAdminCadastrar1();
            } catch (FontFormatException ex) {
                Logger.getLogger(Tela_Admin2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Tela_Admin2.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_buttonCadastrarActionPerformed
    //altera o texto pra frente ao passar o mouse por cima do botao
    private void buttonCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarMouseEntered
        // TODO add your handling code here:
        if(buttonCadastrar.getText().equals("> Cadastrar"))
        buttonCadastrar.setText(">  Cadastrar");
    }//GEN-LAST:event_buttonCadastrarMouseEntered
    //altera o texto de volta para a posicao padrao ao tirar o mouse de cima do botao
    private void buttonCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarMouseExited
        // TODO add your handling code here:
        if(buttonCadastrar.getText().equals(">  Cadastrar"))
            buttonCadastrar.setText("> Cadastrar");
    }//GEN-LAST:event_buttonCadastrarMouseExited
//Fim dos comandos do botao "> Cadastrar"
    
//---------------------------------------------------------------------------------------------------------------------------------

//Inicio dos comandos do botao CRUD
    //altera o texto pra frente ao passar o mouse por cima do botao
    private void buttonCrudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCrudMouseEntered
        // TODO add your handling code here:
        if(buttonCrud.getText().equals("> Editar, Consultar ou Excluir"))
            buttonCrud.setText(">  Editar, Consultar ou Excluir");
    }//GEN-LAST:event_buttonCrudMouseEntered
    //altera o texto de volta para a posicao padrao ao tirar o mouse de cima do botao
    private void buttonCrudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCrudMouseExited
        // TODO add your handling code here:
        if (buttonCrud.getText().equals(">  Editar, Consultar ou Excluir"))
            buttonCrud.setText("> Editar, Consultar ou Excluir");
    }//GEN-LAST:event_buttonCrudMouseExited
    //<null>
    private void buttonCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrudActionPerformed
            try {
                // TODO add your handling code here:
                abrirTelaAdminCrud1();
            } catch (FontFormatException ex) {
                Logger.getLogger(Tela_Admin2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Tela_Admin2.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_buttonCrudActionPerformed

    private void buttonXTelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXTelasMouseEntered
        // TODO add your handling code here:
        ImageIcon XTelasVerm = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/XFecharTelasAdmin2.png"));
        buttonXTelas.setIcon(XTelasVerm);
    }//GEN-LAST:event_buttonXTelasMouseEntered

    private void buttonXTelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXTelasMouseExited
        // TODO add your handling code here:
        ImageIcon XTelas = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/XFecharTelasAdmin.png"));
        buttonXTelas.setIcon(XTelas);
    }//GEN-LAST:event_buttonXTelasMouseExited

    private void buttonXTelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXTelasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonXTelasActionPerformed
//Fim dos comandos do botao CRUD

//---------------------------------------------------------------------------------------------------------------------------------

//metodos typpingEffect para criar o efeito das mensagens serem escritas
private static void typingEffect(JLabel label, String message, JButton bt1, JButton bt2) 
{
    Timer timer = new Timer(25, new ActionListener() 
    {
        private int index = 0;

        @Override
        public void actionPerformed(ActionEvent e) 
        {
            if (index < message.length()) 
            {
                label.setText(label.getText() + message.charAt(index));
                index++;
            }
            else 
            {
                ((Timer) e.getSource()).stop();
                bt1.setVisible(true);
                typingEffectButton(bt1, "> Cadastrar", bt2); 
            }
        }
    });
    timer.start();
}

private static void typingEffectButton(JButton button, String message, JButton bt2) 
{
    button.setText("");
    
    Timer timer = new Timer(25, new ActionListener() 
    {
        private int index = 0;

        @Override
        public void actionPerformed(ActionEvent e) 
        {
            if (index < message.length()) 
            {
                button.setText(button.getText() + message.charAt(index));
                index++;
            }
            else
            {
                ((Timer) e.getSource()).stop();
                bt2.setVisible(true);
                typingEffectButton2(bt2, "> Editar, Consultar ou Excluir");
            }
        }
    });
    timer.start();
}

private static void typingEffectButton2(JButton button, String message) 
{
    button.setText("");
    
    Timer timer = new Timer(25, new ActionListener() 
    {
        private int index = 0;

        @Override
        public void actionPerformed(ActionEvent e) 
        {
            if (index < message.length()) 
            {
                button.setText(button.getText() + message.charAt(index));
                index++;
            }
            else
            {
                ((Timer) e.getSource()).stop();
            }
        }
    });
    timer.start();
}

//---------------------------------------------------------------------------------------------------------------------------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Admin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_Admin2().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(Tela_Admin2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Tela_Admin2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonCrud;
    private javax.swing.JButton buttonXTelas;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JPanel telaAdmin;
    // End of variables declaration//GEN-END:variables
}