//@author @pkmelo7

package com.mycompany.telas.admin;

//Importações necessárias
import com.mycompany.classes.Admin;
import com.mycompany.classes.Usuario;
import com.mycompany.telas.Tela_Cadastro;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
//Fim das importações necessárias

public class Tela_AdminCadastrarUser extends javax.swing.JFrame {
    
    //Declaração de variáveis 
        //variavel para uso da fonte digital7
        Font digital7;
        GraphicsEnvironment GE = GraphicsEnvironment.getLocalGraphicsEnvironment();
        
        //Variável para determinar se o checkbox que torna a senha visivel esta ativo ou nao
        boolean showing = false;
        
        //Variavel para trazer o icone do projeto
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/icon.png")); 
        
        Usuario usuario = new Usuario();
        Admin adm = new Admin();
        
        MaskFormatter mask;
        
        Timer timerAlerta;
        
        boolean cadastrado = false;
        
        boolean acaoConcluida = false;
        
        boolean check = false;
        
        boolean admin = false;
    //Final da declaração de variáveis
    
    //Declaração de métodos
        
        public void abrirTelaAnterior() throws FontFormatException, IOException
        {
            Tela_AdminCadastrar1 TelaAnterior = new Tela_AdminCadastrar1();
            TelaAnterior.setVisible(true);
            this.dispose();
        }
   
    //Fim da declaração de métodos
        
    public Tela_AdminCadastrarUser() throws FontFormatException, IOException {
        //cria a fonte digital7 no projeto
        this.digital7 = Font.createFont(Font.TRUETYPE_FONT, new File("src/main/resources/fonts/digital-7.ttf"));
        initComponents();
        configurarCampoEmail();
        configurarCampoUser();
        
        try
        {
            mask = new MaskFormatter("##/##/####");
            mask.setPlaceholderCharacter('_');
            fieldNasc.setFormatterFactory(new DefaultFormatterFactory(mask));
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonXTelas = new javax.swing.JButton();
        panelAlerta = new javax.swing.JPanel();
        panelAlerta2 = new javax.swing.JPanel();
        labelAlerta = new javax.swing.JLabel();
        buttonOkAlerta = new javax.swing.JButton();
        labelContagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        messageLabel1 = new javax.swing.JLabel();
        telaAdmin = new javax.swing.JPanel();
        buttonVoltar = new javax.swing.JButton();
        buttonCadastrar = new javax.swing.JButton();
        fieldNome = new javax.swing.JTextField();
        labelTxtNasc = new javax.swing.JLabel();
        labelNasc = new javax.swing.JLabel();
        fieldNasc = new javax.swing.JFormattedTextField();
        fieldUser = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        checkboxSenha = new javax.swing.JCheckBox();
        fieldSenha = new javax.swing.JPasswordField();
        labelUser = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        checkboxAdmin = new javax.swing.JCheckBox();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Synapse Connect");
        setBackground(new java.awt.Color(224, 222, 222));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(icon.getImage());
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 750));
        getContentPane().setLayout(null);

        buttonXTelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/XFecharTelasAdmin.png"))); // NOI18N
        buttonXTelas.setBorder(null);
        buttonXTelas.setBorderPainted(false);
        buttonXTelas.setContentAreaFilled(false);
        buttonXTelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXTelas.setFocusPainted(false);
        buttonXTelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonXTelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonXTelasMouseExited(evt);
            }
        });
        buttonXTelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXTelasActionPerformed(evt);
            }
        });
        getContentPane().add(buttonXTelas);
        buttonXTelas.setBounds(1280, 0, 86, 25);

        panelAlerta.setOpaque(false);
        panelAlerta.setVisible(false);
        panelAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAlertaMouseClicked(evt);
            }
        });
        panelAlerta.setLayout(null);

        panelAlerta2.setBackground(new java.awt.Color(0, 0, 0));
        panelAlerta2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 8), 1, true));
        panelAlerta2.setForeground(new java.awt.Color(0, 255, 8));
        panelAlerta2.setLayout(null);

        labelAlerta.setFont(digital7.deriveFont(23f));
        labelAlerta.setForeground(new java.awt.Color(0, 255, 8));
        labelAlerta.setHorizontalAlignment(SwingConstants.CENTER);
        panelAlerta2.add(labelAlerta);
        labelAlerta.setBounds(7, 66, 490, 110);

        buttonOkAlerta.setBackground(new java.awt.Color(0, 0, 0));
        buttonOkAlerta.setFont(digital7.deriveFont(20f));
        buttonOkAlerta.setForeground(new java.awt.Color(0, 255, 8));
        buttonOkAlerta.setText("OK");
        buttonOkAlerta.setBorder(null);
        buttonOkAlerta.setBorderPainted(false);
        buttonOkAlerta.setContentAreaFilled(false);
        buttonOkAlerta.setFocusable(false);
        buttonOkAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonOkAlertaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonOkAlertaMouseExited(evt);
            }
        });
        panelAlerta2.add(buttonOkAlerta);
        buttonOkAlerta.setBounds(355, 210, 100, 40);

        labelContagem.setBackground(new java.awt.Color(0, 0, 0));
        labelContagem.setFont(digital7.deriveFont(20f));
        labelContagem.setForeground(new java.awt.Color(0, 255, 8));
        labelContagem.setText("Tempo Restante: 5");
        labelContagem.setHorizontalAlignment(SwingConstants.RIGHT);
        panelAlerta2.add(labelContagem);
        labelContagem.setBounds(87, 210, 260, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FundosTelas/janelaAlertaAdmin.png"))); // NOI18N
        panelAlerta2.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 281);

        panelAlerta.add(panelAlerta2);
        panelAlerta2.setBounds(433, 243, 500, 281);

        getContentPane().add(panelAlerta);
        panelAlerta.setBounds(0, 0, 1366, 768);

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setLayout(null);

        messageLabel1.setBackground(new java.awt.Color(0, 0, 0));
        messageLabel1.setFont(digital7.deriveFont(100f));
        messageLabel1.setForeground(new java.awt.Color(0, 255, 8));
        messageLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        messageLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        String message = "Cadastro de usuarios";
        typingEffect(messageLabel1, message, buttonVoltar, telaAdmin);
        panel.add(messageLabel1);
        messageLabel1.setBounds(0, 0, 1366, 201);

        telaAdmin.setBackground(new java.awt.Color(0, 0, 0));
        telaAdmin.setForeground(new java.awt.Color(0, 0, 0));
        telaAdmin.setVisible(false);
        telaAdmin.setLayout(null);

        buttonVoltar.setBackground(new java.awt.Color(0, 0, 0));
        buttonVoltar.setFont(digital7.deriveFont(50f));
        buttonVoltar.setForeground(new java.awt.Color(0, 255, 8));
        buttonVoltar.setBorder(null);
        buttonVoltar.setBorderPainted(false);
        buttonVoltar.setContentAreaFilled(false);
        buttonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonVoltar.setFocusPainted(false);
        buttonVoltar.setHorizontalAlignment(SwingConstants.LEFT);
        buttonVoltar.setVisible(false);
        buttonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonVoltarMouseExited(evt);
            }
        });
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        telaAdmin.add(buttonVoltar);
        buttonVoltar.setBounds(16, 700, 240, 60);

        buttonCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        buttonCadastrar.setFont(digital7.deriveFont(75f));
        buttonCadastrar.setForeground(new java.awt.Color(0, 255, 8));
        buttonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/CadastrarAdmin.png"))); // NOI18N
        buttonCadastrar.setBorder(null);
        buttonCadastrar.setBorderPainted(false);
        buttonCadastrar.setContentAreaFilled(false);
        buttonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCadastrar.setFocusPainted(false);
        buttonCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCadastrarMouseExited(evt);
            }
        });
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        telaAdmin.add(buttonCadastrar);
        buttonCadastrar.setBounds(1044, 632, 200, 70);

        fieldNome.setBackground(new java.awt.Color(0, 0, 0));
        fieldNome.setFont(digital7.deriveFont(25f));
        fieldNome.setForeground(new java.awt.Color(0, 178, 6));
        fieldNome.setText("Nome");
        fieldNome.setBorder(null);
        fieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNomeFocusLost(evt);
            }
        });
        telaAdmin.add(fieldNome);
        fieldNome.setBounds(190, 217, 1030, 50);

        labelTxtNasc.setForeground(new java.awt.Color(204, 0, 0));
        telaAdmin.add(labelTxtNasc);
        labelTxtNasc.setBounds(190, 360, 260, 20);

        labelNasc.setBackground(new java.awt.Color(0, 0, 0));
        labelNasc.setFont(digital7.deriveFont(25f));
        labelNasc.setForeground(new java.awt.Color(0, 178, 6));
        labelNasc.setText("Nascimento");
        labelNasc.setOpaque(true);
        telaAdmin.add(labelNasc);
        labelNasc.setBounds(190, 303, 370, 50);

        fieldNasc.setBackground(new java.awt.Color(0, 0, 0));
        fieldNasc.setBorder(null);
        fieldNasc.setForeground(new java.awt.Color(0, 255, 8));
        fieldNasc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldNasc.setToolTipText("");
        fieldNasc.setFont(digital7.deriveFont(25f));
        fieldNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNascFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNascFocusLost(evt);
            }
        });
        telaAdmin.add(fieldNasc);
        fieldNasc.setBounds(190, 303, 1030, 50);

        fieldUser.setBackground(new java.awt.Color(0, 0, 0));
        fieldUser.setFont(digital7.deriveFont(25f));
        fieldUser.setForeground(new java.awt.Color(0, 178, 6));
        fieldUser.setText("Usuario");
        fieldUser.setBorder(null);
        telaAdmin.add(fieldUser);
        fieldUser.setBounds(190, 388, 1030, 50);

        fieldEmail.setBackground(new java.awt.Color(0, 0, 0));
        fieldEmail.setFont(digital7.deriveFont(25f));
        fieldEmail.setForeground(new java.awt.Color(0, 178, 6));
        fieldEmail.setText("E-mail");
        fieldEmail.setBorder(null);
        telaAdmin.add(fieldEmail);
        fieldEmail.setBounds(190, 473, 1030, 50);

        labelSenha.setBackground(new java.awt.Color(0, 0, 0));
        labelSenha.setFont(digital7.deriveFont(25f));
        labelSenha.setForeground(new java.awt.Color(0, 178, 6));
        labelSenha.setText("Senha");
        telaAdmin.add(labelSenha);
        labelSenha.setBounds(190, 559, 150, 50);

        checkboxSenha.setBackground(new java.awt.Color(0, 0, 0));
        checkboxSenha.setFont(digital7.deriveFont(25f));
        checkboxSenha.setForeground(new java.awt.Color(0, 255, 8));
        checkboxSenha.setBorder(null);
        checkboxSenha.setContentAreaFilled(false);
        checkboxSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkboxSenha.setFocusPainted(false);
        checkboxSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/SenhaMostrarAdmin.png"))); // NOI18N
        checkboxSenha.setVisible(false);
        checkboxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxSenhaActionPerformed(evt);
            }
        });
        telaAdmin.add(checkboxSenha);
        checkboxSenha.setBounds(1200, 559, 20, 50);

        fieldSenha.setBackground(new java.awt.Color(0, 0, 0));
        fieldSenha.setFont(digital7.deriveFont(25f));
        fieldSenha.setForeground(new java.awt.Color(0, 255, 8));
        fieldSenha.setBorder(null);
        fieldSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldSenhaFocusLost(evt);
            }
        });
        fieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSenhaKeyReleased(evt);
            }
        });
        telaAdmin.add(fieldSenha);
        fieldSenha.setBounds(190, 559, 1030, 50);

        labelUser.setForeground(new java.awt.Color(204, 0, 0));
        telaAdmin.add(labelUser);
        labelUser.setBounds(190, 446, 260, 20);

        labelEmail.setText("Formato: exemplo@dominio.com");
        telaAdmin.add(labelEmail);
        labelEmail.setBounds(190, 526, 320, 30);

        checkboxAdmin.setFont(digital7.deriveFont(25f));
        checkboxAdmin.setForeground(new java.awt.Color(0, 255, 8));
        checkboxAdmin.setText("Cadastrar Usuario como admin?");
        checkboxAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Botoes/checkboxFAdm.png"))); // NOI18N
        checkboxAdmin.setHorizontalAlignment(SwingConstants.RIGHT);
        checkboxAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAdminActionPerformed(evt);
            }
        });
        telaAdmin.add(checkboxAdmin);
        checkboxAdmin.setBounds(655, 650, 370, 40);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FundosTelas/FundoCadastrarAdmin.png"))); // NOI18N
        telaAdmin.add(fundo);
        fundo.setBounds(0, 0, 1366, 768);

        panel.add(telaAdmin);
        telaAdmin.setBounds(0, 0, 1366, 768);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 1366, 768);

        setBounds(-6, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents
//---------------------------------------------------------------------------------------------------------------------------------

//Inicio dos comandos do botao Cursos
    //altera o texto pra frente ao passar o mouse por cima do botao
    private void buttonCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarMouseEntered
        // TODO add your handling code here:
        ImageIcon Cadastrar2 = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/CadastrarAdmin2.png"));
        buttonCadastrar.setIcon(Cadastrar2);
    }//GEN-LAST:event_buttonCadastrarMouseEntered
    //altera o texto de volta para a posicao padrao ao tirar o mouse de cima do botao
    private void buttonCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCadastrarMouseExited
        // TODO add your handling code here:
        ImageIcon Cadastrar = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/CadastrarAdmin.png"));
        buttonCadastrar.setIcon(Cadastrar);
    }//GEN-LAST:event_buttonCadastrarMouseExited
    //<null>
    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        // TODO add your handling code here:
        String nome = null;
        String nasc = null;
        String usu = null; 
        String email = null;
        String senha = null;
        
        if(fieldNome.getText().equals("Nome") || fieldNome.getText().equals(""))
        {
            labelAlerta.setText("Nome vazio, por favor preencha.");
            mensagemErro();
        }
        else
        {
            nome = fieldNome.getText();
        }
        
        if(fieldNasc.getText().equals("") || labelNasc.isVisible())
        {
            labelAlerta.setText("Nascimento vazio, por favor preencha.");
            mensagemErro();
        }
        else
        {
            if (!validarData(fieldNasc.getText())) 
            {
                labelAlerta.setText("Data invalida, tente novamente.");
                mensagemErro();
            }
            else
            {
               nasc = fieldNasc.getText();
            }
        }
        
        if(fieldUser.getText().equals("Usuario") || fieldUser.getText().equals(""))
        {
            labelAlerta.setText("Usuario vazio, por favor preencha.");
            mensagemErro();
        }
        else
        {
            usu = fieldUser.getText();
        }
        
        if(fieldEmail.getText().equals("E-mail") || fieldEmail.getText().equals(""))
        {
            labelAlerta.setText("Email vazio, por favor preencha.");
            mensagemErro();
        }
        else
        {
            if (!validarEmail(fieldEmail.getText())) 
            {
                labelAlerta.setText("Email invalido, tente novamente.");
                mensagemErro();
            }
            else
            {
               email = fieldEmail.getText();
            }   
        }
        
        if(fieldSenha.getText().equals("Senha") || fieldSenha.getText().equals(""))
        {
            labelAlerta.setText("Senha vazia, por favor preencha.");
            mensagemErro();
        }
        else
        {
            senha = fieldSenha.getText();
        }
        
        usuario.setNome(nome);
        usuario.setDtnasc(nasc);
        usuario.setUser(usu);
        usuario.setEmail(email);
        usuario.setSenha(senha);
        
        try 
        {
            // Verifica se o usuário ou email já existem
            if (usuario.verificaUserExiste()) 
            {
                labelAlerta.setText("Usuario ja cadastrado, tente novamente.");
                mensagemErro();
            }
            else if(usuario.verificaEmailExiste())
            {
                labelAlerta.setText("E-mail ja cadastrado, tente novamente.");
                mensagemErro();
            }
            else 
            {
                if(checkboxAdmin.isSelected())
                {
                    if(usuario.cadastraAdmin())
                    {
                        cadastrado = true;
                        labelAlerta.setText("Administrador cadastrado com sucesso.");
                        mensagemErro();
                    }
                    else
                    {
                        System.out.println("Erro ao cadastrar");
                    }
                }
                else
                {
                    // Cadastra o novo usuário
                    if (usuario.cadastraUser()) 
                    {
                        cadastrado = true;
                        labelAlerta.setText("Usuario cadastrado com sucesso.");
                        mensagemErro();
                    }
                    else
                    {
                        System.out.println("Erro ao cadastar");
                    }
                    
                }
            }
        }
        catch (SQLException e) 
        {
            e.printStackTrace();
            System.out.println("Erro ao acessar o banco de dados.");
        }
        
             
    }//GEN-LAST:event_buttonCadastrarActionPerformed
    
    private void mensagemErro()
    {        
         // Garantir que o painel esteja visível após a exclusão
        panelAlerta.setVisible(true);

        // Revalide o layout para garantir que o painel seja renderizado corretamente
        panelAlerta.revalidate();
        panelAlerta.repaint();

        // Definir tempo inicial da contagem regressiva
        final int tempoInicial = 5;
        final int[] tempoRestante = {tempoInicial}; // Usamos um array para poder alterar o valor dentro do Timer

        // **Cancelar o Timer anterior, se houver** (importante para a segunda, terceira exclusão, etc.)
        if (timerAlerta != null && timerAlerta.isRunning()) 
        {
            timerAlerta.stop();  // Para o Timer atual, se já estiver em execução
        }

        // Criar o Timer para a contagem regressiva
        timerAlerta = new Timer(1000, new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                // Atualiza o texto da contagem regressiva
                if (tempoRestante[0] > 0) 
                {
                    tempoRestante[0]--;
                    labelContagem.setText("Tempo restante: " + tempoRestante[0]);
                } 
                else
                {
                    // Quando a contagem chega a 0, reinicia o tempo
                    tempoRestante[0] = tempoInicial; // Reinicia para 5 segundos
                    labelContagem.setText("Tempo restante: " + tempoRestante[0]);

                    // Esconde o painel após a contagem
                    panelAlerta.setVisible(false);

                    // Para o Timer
                    timerAlerta.stop();

                    acaoConcluida = true;
                    
                    if(cadastrado != false)
                    {
                        limparCampos();
                    }
                    else
                    {
                        System.out.println("usuario nao cadastrado");
                    }
                }
            }
        });

        // Inicia o Timer de contagem regressiva
        timerAlerta.start();

        // Ação do botão "OK" para fechar o painel antes do tempo
        buttonOkAlerta.addActionListener(new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) 
            {
                // Para o Timer imediatamente
                if (timerAlerta != null) 
                {
                    timerAlerta.stop();
                }

                // Esconde o painel imediatamente
                panelAlerta.setVisible(false);

                acaoConcluida = true;
                
                if(cadastrado != false)
                    {
                        limparCampos();
                    }
                else
                {
                    System.out.println("usuario nao cadastrado");
                }

                // Opcional: Resetar a contagem se necessário (reiniciar a contagem para o próximo uso)
                tempoRestante[0] = tempoInicial; // Reinicia a contagem
                labelContagem.setText("Tempo restante: " + tempoRestante[0]);
            }
        });
    }
    
    private void limparCampos() 
    {
        fieldNome.setText("Nome");
        fieldNome.setForeground(new Color(0,178,6));
        fieldNasc.setText("");
        labelNasc.setVisible(true);
        fieldUser.setText("Usuario");
        fieldUser.setForeground(new Color(0,178,6));
        labelUser.setText("");
        fieldEmail.setText("E-mail");
        fieldSenha.setText("");
        labelSenha.setText("Senha");
    }

//Fim dos comandos do botao Cursos

//---------------------------------------------------------------------------------------------------------------------------------


    private void buttonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarMouseEntered
        // TODO add your handling code here:
        if(buttonVoltar.getText().equals("<-- Voltar"))
            buttonVoltar.setText("<--  Voltar");
    }//GEN-LAST:event_buttonVoltarMouseEntered

    private void buttonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonVoltarMouseExited
        // TODO add your handling code here:
        if (buttonVoltar.getText().equals("<--  Voltar"))
            buttonVoltar.setText("<-- Voltar");
    }//GEN-LAST:event_buttonVoltarMouseExited

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
            try {
                // TODO add your handling code here:
                abrirTelaAnterior();
            } catch (FontFormatException ex) {
                Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void fieldNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNomeFocusGained
        // TODO add your handling code here:
        if (fieldNome.getText().equals("Nome")) {
            fieldNome.setText("");
            fieldNome.setForeground(new Color(0,255,8));
        }
    }//GEN-LAST:event_fieldNomeFocusGained

    private void fieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNomeFocusLost
        // TODO add your handling code here:
        if (fieldNome.getText().isEmpty()) {
            fieldNome.setForeground(new Color(0,178,6));
            fieldNome.setText("Nome");
        }
    }//GEN-LAST:event_fieldNomeFocusLost
     
    private void configurarCampoUser() {
       // Adicionar um ouvinte de foco para limpar e restaurar o texto de placeholder
        fieldUser.addFocusListener(new FocusListener() 
        {
            public void focusGained(FocusEvent e) 
            {
                // Quando o campo recebe foco, limpar o texto (se for o placeholder)
                if (fieldUser.getText().equals("Usuario")) 
                {
                    fieldUser.setText("");
                    fieldUser.setForeground(new Color(0, 255, 8)); // Cor verde, por exemplo
                }
            }

            public void focusLost(FocusEvent e) 
            {
                if (fieldUser.getText().isEmpty()) 
                {
                    fieldUser.setForeground(new Color(0,178,6));
                    fieldUser.setText("Usuario");
                    labelUser.setText("");
                }
                else
                {  
                    String usu = fieldUser.getText();
                    usuario.setUser(usu);
                    try
                    {
                        if(usuario.verificaUserExiste())
                        {
                            labelUser.setText("*Usuario já cadastrado");
                            labelUser.setForeground(Color.red);
                        }
                        else
                        {
                            labelUser.setText("*Usuario válido");
                            labelUser.setForeground(new Color(0,255,8));
                        }
                    } 
                    catch (SQLException ex) 
                    {
                        Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }
    
    private void configurarCampoEmail() 
    {
        // Texto placeholder
        fieldEmail.setText("E-mail");
        fieldEmail.setForeground(new Color(0,178,6)); // Cor mais suave para o placeholder

        // Inicializar o JLabel com o texto inicial de formato
        labelEmail.setText("Formato: exemplo@dominio.com");
        labelEmail.setForeground(new Color(153, 153, 153)); // Cor mais suave para o formato
      
        // Adicionar um ouvinte de foco para limpar e restaurar o texto de placeholder
        fieldEmail.addFocusListener(new FocusListener() 
        {
            public void focusGained(FocusEvent e) 
            {
                // Quando o campo recebe foco, limpar o texto (se for o placeholder)
                if (fieldEmail.getText().equals("E-mail")) 
                {
                    fieldEmail.setText("");
                    fieldEmail.setForeground(new Color(0, 255, 8)); // Cor verde, por exemplo
                }
            }

            public void focusLost(FocusEvent e) {
                // Se o campo estiver vazio, restaurar o texto de placeholder
                if (fieldEmail.getText().isEmpty()) {
                    fieldEmail.setText("E-mail");
                    fieldEmail.setForeground(new Color(0,178,6)); // Cor mais suave para o placeholder
                    labelEmail.setText("Formato: exemplo@dominio.com"); // Exibir o formato padrão
                    labelEmail.setForeground(new Color(153, 153, 153)); // Cor suave
                } 
                else 
                {
                    // Se o campo não estiver vazio, validação de formato
                    if (!validarEmail(fieldEmail.getText())) 
                    {
                        labelEmail.setText("Formato de e-mail inválido! Use exemplo@dominio.com.");
                        labelEmail.setForeground(Color.RED); // Cor vermelha para erro
                    } 
                    else
                    {
                        String email = fieldEmail.getText();
                        usuario.setEmail(email);
                        try 
                        {
                            if(usuario.verificaEmailExiste())
                            {
                                labelEmail.setText("*E-mail já cadastrado");
                                labelEmail.setForeground(Color.RED);
                            }
                            else
                            {   
                                labelEmail.setText("*E-mail válido");
                                labelEmail.setForeground(new Color(0,255,8));
                            }
                        }
                        catch (SQLException ex) 
                        {
                            Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        });
    }
 
    private boolean validarEmail(String email)
    {
        return email.matches("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}");
    }
    
    
    private void fieldSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSenhaFocusGained
        // TODO add your handling code here:
        if (labelSenha.getText().equals("Senha")) {
            labelSenha.setText("");
            fieldSenha.setForeground(new Color(0,255,8));
        }
    }//GEN-LAST:event_fieldSenhaFocusGained

    private void fieldSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldSenhaFocusLost
        // TODO add your handling code here:
        if (labelSenha.getText().isEmpty() || fieldSenha.getText().isEmpty()) {
            labelSenha.setForeground(new Color(0,178,6));
            labelSenha.setText("Senha");
        }
    }//GEN-LAST:event_fieldSenhaFocusLost

    private void fieldSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSenhaKeyReleased
        // TODO add your handling code here:
        if (fieldSenha.getPassword().length > 0)
        {
            labelSenha.setText(" ");
            checkboxSenha.setVisible(true);
            Icon MostrarSenha = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/SenhaMostrarAdmin.png"));
            checkboxSenha.setIcon(MostrarSenha);
        }
        else
        {
            checkboxSenha.setVisible(false);
        }
    }//GEN-LAST:event_fieldSenhaKeyReleased

    private void checkboxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxSenhaActionPerformed
        // TODO add your handling code here:
        Icon OcultarSenha = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/SenhaOcultarAdmin.png"));
        Icon MostrarSenha = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/SenhaMostrarAdmin.png"));

        if(showing)
        {
            fieldSenha.setEchoChar('*');
            checkboxSenha.setIcon(MostrarSenha);
        }
        else
        {
            fieldSenha.setEchoChar((char) 0);
            checkboxSenha.setIcon(OcultarSenha);
        }
        showing = !showing;
    }//GEN-LAST:event_checkboxSenhaActionPerformed

    private void fieldNascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNascFocusGained
        // TODO add your handling code here:
        labelNasc.setVisible(false);
    }//GEN-LAST:event_fieldNascFocusGained

    private void fieldNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNascFocusLost
        // TODO add your handling code here:
        String data = fieldNasc.getText();
        
        if (fieldNasc.getText().equals("__/__/____")) 
        {
            labelNasc.setVisible(true);
            labelTxtNasc.setText("");
            data = null;
        }
        
        if(!validarData(data))
        {
            labelTxtNasc.setText("*Data inválida, informe uma data válida.");           
        }
        else
        {
            labelTxtNasc.setText("");           
        }
    }//GEN-LAST:event_fieldNascFocusLost

    private void buttonOkAlertaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkAlertaMouseEntered
        // TODO add your handling code here:
        buttonOkAlerta.setFont(digital7.deriveFont(25f));
    }//GEN-LAST:event_buttonOkAlertaMouseEntered

    private void buttonOkAlertaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkAlertaMouseExited
        // TODO add your handling code here:
        buttonOkAlerta.setFont(digital7.deriveFont(20f));
    }//GEN-LAST:event_buttonOkAlertaMouseExited

    private void panelAlertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAlertaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAlertaMouseClicked

    private void buttonXTelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXTelasMouseEntered
        // TODO add your handling code here:
        ImageIcon XTelasVerm = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/XFecharTelasAdmin2.png"));
        buttonXTelas.setIcon(XTelasVerm);
    }//GEN-LAST:event_buttonXTelasMouseEntered

    private void buttonXTelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonXTelasMouseExited
        // TODO add your handling code here:
        ImageIcon XTelas = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/XFecharTelasAdmin.png"));
        buttonXTelas.setIcon(XTelas);
    }//GEN-LAST:event_buttonXTelasMouseExited

    private void buttonXTelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXTelasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonXTelasActionPerformed

    private void checkboxAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAdminActionPerformed
        // TODO add your handling code here:
        Icon adminT = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/checkboxTAdm.png"));
        Icon adminF = new ImageIcon(getClass().getClassLoader().getResource("images/Botoes/checkboxFAdm.png"));

        if(check)
        {
            checkboxAdmin.setIcon(adminF);
            admin = false;
        }
        else
        {
            checkboxAdmin.setIcon(adminT);
            admin = true;
        }
        check = !check;
    }//GEN-LAST:event_checkboxAdminActionPerformed

    public boolean validarData(String data) 
    {
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            format.setLenient(false); // Para garantir que a data seja válida
            // Parse da data fornecida
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(format.parse(data)); 

            // Obtém o ano da data fornecida
            int anoData = calendar.get(Calendar.YEAR);
            
            // Obtém o ano atual
            int anoAtual = Calendar.getInstance().get(Calendar.YEAR);
            
            // Verifica se o ano é menor que o ano atual
            if (anoData > anoAtual) {
                return false; // Ano da data é menor que o ano atual
            }
            
            return true; // A data é válida e o ano é igual ou maior que o ano atual
        } catch (ParseException e) {
            return false; // Caso ocorra um erro no parse, a data é inválida
        }
    }
//---------------------------------------------------------------------------------------------------------------------------------

//metodos typpingEffect para criar o efeito das mensagens serem escritas
private static void typingEffect(JLabel label, String message, JButton bt1, JPanel panel) 
{
    Timer timer = new Timer(25, new ActionListener() 
    {
        private int index = 0;

        @Override
        public void actionPerformed(ActionEvent e) 
        {
            if (index < message.length()) 
            {
                label.setText(label.getText() + message.charAt(index));
                index++;
            }
            else 
            {
                ((Timer) e.getSource()).stop();
                panel.setVisible(true);
                bt1.setVisible(true);
                typingEffect(bt1, "<-- Voltar"); 
            }
        }
    });
    timer.start();
}

private static void typingEffect(JButton button, String message) 
{
    button.setText("");
    
    Timer timer = new Timer(25, new ActionListener() 
    {
        private int index = 0;

        @Override
        public void actionPerformed(ActionEvent e) 
        {
            if (index < message.length()) 
            {
                button.setText(button.getText() + message.charAt(index));
                index++;
            }
            else
            {
                ((Timer) e.getSource()).stop();
            }
        }
    });
    timer.start();
}


//---------------------------------------------------------------------------------------------------------------------------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_AdminCadastrarUser().setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Tela_AdminCadastrarUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonOkAlerta;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JButton buttonXTelas;
    private javax.swing.JCheckBox checkboxAdmin;
    private javax.swing.JCheckBox checkboxSenha;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JFormattedTextField fieldNasc;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAlerta;
    private javax.swing.JLabel labelContagem;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNasc;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTxtNasc;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelAlerta;
    private javax.swing.JPanel panelAlerta2;
    private javax.swing.JPanel telaAdmin;
    // End of variables declaration//GEN-END:variables
}